name: Matrix with Node.js
on:
  push:
  workflow_dispatch:
jobs:
  build:
    strategy:
      matrix:
        node-version: [14, 16, 17]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm test
